import { Form, Row, Col, FormControl } from "react-bootstrap";
import ListadoNoticias from "./ListaNoticias";

const FormularioNoticias = () => {
  return (
    <>
      <section className="sectionForm mx-auto px-2 rounded-3 bg-white ">
        <Form className="form pt-5">
          <Form.Group
            as={Row}
            className="mb-2 mb-md-3 d-flex justify-content-center h-100"
          >
            <Form.Label column sm="4">
              Buscar por categoría:
            </Form.Label>
            <Col md="5">
              <Form.Select required>
                <option>seleccione</option>
                <option value="Entretenimiento">Entrenimiento</option>
                <option value="Tecnologia">Tecnología</option>
                <option value="Negocio">Negocio</option>
                <option value="Política">Política</option>
                <option value="Deportes">Deportes</option>
                <option value="Salud">Salud</option>
                <option value="Delito">Delito</option>
                <option value="Domestico">Doméstico</option>
                <option value="Educación">Educación</option>
                <option value="Ambiente">Ambiente</option>
                <option value="Comida">Comida</option>
                <option value="Estilo de vida">Estilo de vida</option>
                <option value="Ciencia">Ciencia</option>
                <option value="Turismo">Turismo</option>
                <option value="Mundo">Mundo</option>
                <option value="Arriba">Arriba</option>
                <option value="Otro">Otro</option>
              </Form.Select>
            </Col>
            <Form.Label column sm="4">
              Selecciona o ingresa un país:
            </Form.Label>
            <Col md="5">
              <FormControl list="countries" id="country" name="country" />
              <datalist id="countries">
                <option value="Afganistán"></option>
                <option value="Albania"></option>
                <option value="Argelia"></option>
                <option value="Samoa Americana"></option>
                <option value="Andorra"></option>
                <option value="Angola"></option>
                <option value="Anguilla"></option>
                <option value="Antártida"></option>
                <option value="Antigua y Barbuda"></option>
                <option value="Argentina"></option>
                <option value="Armenia"></option>
                <option value="Aruba"></option>
                <option value="Australia"></option>
                <option value="Austria"></option>
                <option value="Azerbaiyán"></option>
                <option value="Bahamas"></option>
                <option value="Baréin"></option>
                <option value="Bangladés"></option>
                <option value="Barbados"></option>
                <option value="Bielorrusia"></option>
                <option value="Bélgica"></option>
                <option value="Belice"></option>
                <option value="Benín"></option>
                <option value="Bermudas"></option>
                <option value="Bután"></option>
                <option value="Bolivia"></option>
                <option value="Bosnia y Herzegovina"></option>
                <option value="Botsuana"></option>
                <option value="Isla Bouvet"></option>
                <option value="Brasil"></option>
                <option value="Territorio Británico del Océano Índico"></option>
                <option value="Brunéi"></option>
                <option value="Bulgaria"></option>
                <option value="Burkina Faso"></option>
                <option value="Burundi"></option>
                <option value="Camboya"></option>
                <option value="Camerún"></option>
                <option value="Canadá"></option>
                <option value="Cabo Verde"></option>
                <option value="Islas Caimán"></option>
                <option value="República Centroafricana"></option>
                <option value="Chad"></option>
                <option value="Chile"></option>
                <option value="China"></option>
                <option value="Isla de Navidad"></option>
                <option value="Islas Cocos"></option>
                <option value="Colombia"></option>
                <option value="Comoras"></option>
                <option value="Congo"></option>
                <option value="República Democrática del Congo"></option>
                <option value="Islas Cook"></option>
                <option value="Costa Rica"></option>
                <option value="Costa de Marfil"></option>
                <option value="Croacia"></option>
                <option value="Cuba"></option>
                <option value="Chipre"></option>
                <option value="República Checa"></option>
                <option value="Dinamarca"></option>
                <option value="Yibuti"></option>
                <option value="Dominica"></option>
                <option value="República Dominicana"></option>
                <option value="Ecuador"></option>
                <option value="Egipto"></option>
                <option value="El Salvador"></option>
                <option value="Guinea Ecuatorial"></option>
                <option value="Eritrea"></option>
                <option value="Estonia"></option>
                <option value="Etiopía"></option>
                <option value="Islas Malvinas"></option>
                <option value="Islas Feroe"></option>
                <option value="Fiyi"></option>
                <option value="Finlandia"></option>
                <option value="Francia"></option>
                <option value="Guayana Francesa"></option>
                <option value="Polinesia Francesa"></option>
                <option value="Territorios Australes Franceses"></option>
                <option value="Gabón"></option>
                <option value="Gambia"></option>
                <option value="Georgia"></option>
                <option value="Alemania"></option>
                <option value="Ghana"></option>
                <option value="Gibraltar"></option>
                <option value="Grecia"></option>
                <option value="Groenlandia"></option>
                <option value="Granada"></option>
                <option value="Guadalupe"></option>
                <option value="Guam"></option>
                <option value="Guatemala"></option>
                <option value="Guernsey"></option>
                <option value="Guinea"></option>
                <option value="Guinea-Bisáu"></option>
                <option value="Guyana"></option>
                <option value="Haití"></option>
                <option value="Islas Heard y McDonald"></option>
                <option value="Santa Sede"></option>
                <option value="Honduras"></option>
                <option value="Hong Kong"></option>
                <option value="Hungría"></option>
                <option value="Islandia"></option>
                <option value="India"></option>
                <option value="Indonesia"></option>
                <option value="Irán"></option>
                <option value="Irak"></option>
                <option value="Irlanda"></option>
                <option value="Isla de Man"></option>
                <option value="Israel"></option>
                <option value="Italia"></option>
                <option value="Jamaica"></option>
                <option value="Japón"></option>
                <option value="Jersey"></option>
                <option value="Jordania"></option>
                <option value="Kazajistán"></option>
                <option value="Kenia"></option>
                <option value="Kiribati"></option>
                <option value="Corea del Norte"></option>
                <option value="Corea del Sur"></option>
                <option value="Kuwait"></option>
                <option value="Kirguistán"></option>
                <option value="Laos"></option>
                <option value="Letonia"></option>
                <option value="Líbano"></option>
                <option value="Lesoto"></option>
                <option value="Liberia"></option>
                <option value="Libia"></option>
                <option value="Liechtenstein"></option>
                <option value="Lituania"></option>
                <option value="Luxemburgo"></option>
                <option value="Macao"></option>
                <option value="Macedonia del Norte"></option>
                <option value="Madagascar"></option>
                <option value="Malaui"></option>
                <option value="Malasia"></option>
                <option value="Maldivas"></option>
                <option value="Mali"></option>
                <option value="Malta"></option>
                <option value="Islas Marshall"></option>
                <option value="Martinica"></option>
                <option value="Mauritania"></option>
                <option value="Mauricio"></option>
                <option value="Mayotte"></option>
                <option value="México"></option>
                <option value="Micronesia"></option>
                <option value="Moldavia"></option>
                <option value="Mónaco"></option>
                <option value="Mongolia"></option>
                <option value="Montenegro"></option>
                <option value="Montserrat"></option>
                <option value="Marruecos"></option>
                <option value="Mozambique"></option>
                <option value="Myanmar"></option>
                <option value="Namibia"></option>
                <option value="Nauru"></option>
                <option value="Nepal"></option>
                <option value="Países Bajos"></option>
                <option value="Nueva Caledonia"></option>
                <option value="Nueva Zelanda"></option>
                <option value="Nicaragua"></option>
                <option value="Níger"></option>
                <option value="Nigeria"></option>
                <option value="Niue"></option>
                <option value="Isla Norfolk"></option>
                <option value="Islas Marianas del Norte"></option>
                <option value="Noruega"></option>
                <option value="Omán"></option>
                <option value="Pakistán"></option>
                <option value="Palaos"></option>
                <option value="Palestina"></option>
                <option value="Panamá"></option>
                <option value="Papúa Nueva Guinea"></option>
                <option value="Paraguay"></option>
                <option value="Perú"></option>
                <option value="Filipinas"></option>
                <option value="Pitcairn"></option>
                <option value="Polonia"></option>
                <option value="Portugal"></option>
                <option value="Puerto Rico"></option>
                <option value="Catar"></option>
                <option value="Reunión"></option>
                <option value="Rumania"></option>
                <option value="Rusia"></option>
                <option value="Ruanda"></option>
                <option value="San Bartolomé"></option>
                <option value="Santa Elena, Ascensión y Tristán de Acuña"></option>
                <option value="San Cristóbal y Nieves"></option>
                <option value="Santa Lucía"></option>
                <option value="San Martín"></option>
                <option value="San Pedro y Miquelón"></option>
                <option value="San Vicente y las Granadinas"></option>
                <option value="Samoa"></option>
                <option value="San Marino"></option>
                <option value="Santo Tomé y Príncipe"></option>
                <option value="Arabia Saudita"></option>
                <option value="Senegal"></option>
                <option value="Serbia"></option>
                <option value="Seychelles"></option>
                <option value="Sierra Leona"></option>
                <option value="Singapur"></option>
                <option value="Sint Maarten"></option>
                <option value="Eslovaquia"></option>
                <option value="Eslovenia"></option>
                <option value="Islas Salomón"></option>
                <option value="Somalia"></option>
                <option value="Sudáfrica"></option>
                <option value="Islas Georgias del Sur y Sandwich del Sur"></option>
                <option value="Sudán del Sur"></option>
                <option value="España"></option>
                <option value="Sri Lanka"></option>
                <option value="Sudán"></option>
                <option value="Surinam"></option>
                <option value="Svalbard y Jan Mayen"></option>
                <option value="Suecia"></option>
                <option value="Suiza"></option>
                <option value="Siria"></option>
                <option value="Taiwán"></option>
                <option value="Tayikistán"></option>
                <option value="Tanzania"></option>
                <option value="Tailandia"></option>
                <option value="Timor Oriental"></option>
                <option value="Togo"></option>
                <option value="Tokelau"></option>
                <option value="Tonga"></option>
                <option value="Trinidad y Tobago"></option>
                <option value="Túnez"></option>
                <option value="Turquía"></option>
                <option value="Turkmenistán"></option>
                <option value="Islas Turcas y Caicos"></option>
                <option value="Tuvalu"></option>
                <option value="Uganda"></option>
                <option value="Ucrania"></option>
                <option value="Emiratos Árabes Unidos"></option>
                <option value="Reino Unido"></option>
                <option value="Estados Unidos de América"></option>
                <option value="Uruguay"></option>
                <option value="Uzbekistán"></option>
                <option value="Vanuatu"></option>
                <option value="Venezuela"></option>
                <option value="Vietnam"></option>
                <option value="Islas Vírgenes Británicas"></option>
                <option value="Islas Vírgenes de los Estados Unidos"></option>
                <option value="Wallis y Futuna"></option>
                <option value="Sáhara Occidental"></option>
                <option value="Yemen"></option>
                <option value="Zambia"></option>
                <option value="Zimbabue"></option>
              </datalist>
            </Col>
          </Form.Group>
        </Form>
      </section>
      <ListadoNoticias></ListadoNoticias>
    </>
  );
};

export default FormularioNoticias;